language: node_js
node_js:
  - lts/*
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: e77f047f7017563a9e516ef6ce31c2b3e509d0d4 # a token generated on github allowing travis to push code on you repository e77f047f7017563a9e516ef6ce31c2b3e509d0d4
  keep-history: true
  on:
    branch: master